import { Sparkle } from "lucide-react";
import type { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    title: "Handmade Soap",
    image: "/images/soap.jpg",
    rating: 4.5,
    reviews: 34,
    features: [
      { icon: <Sparkle className="w-4 h-4" />, text: "Organic Ingredients" },
      { icon: <Sparkle className="w-4 h-4" />, text: "Scented with Lavender" },
    ],
    price: "$12",
    unitPrice: "$4/oz",
    deliveryDate: "May 10",
    shippingLocation: "USA",
  },
  {
    id: 2,
    title: "Beeswax Candles",
    image: "/images/candles.jpg",
    rating: 4.8,
    reviews: 58,
    features: [
      { icon: <Sparkle className="w-4 h-4" />, text: "Slow-burning" },
      { icon: <Sparkle className="w-4 h-4" />, text: "Natural fragrance" },
    ],
    price: "$18",
    unitPrice: "$6/each",
    deliveryDate: "May 12",
    shippingLocation: "Canada",
  },
  {
    id: 3,
    title: "Knitted Scarf",
    image: "/images/scarf.jpg",
    rating: 4.2,
    reviews: 21,
    features: [
      { icon: <Sparkle className="w-4 h-4" />, text: "Soft wool blend" },
      { icon: <Sparkle className="w-4 h-4" />, text: "Hand-stitched" },
    ],
    price: "$30",
    unitPrice: "$30/item",
    deliveryDate: "May 14",
    shippingLocation: "UK",
  },
  {
    id: 4,
    title: "Ceramic Mug",
    image: "/images/mug.jpg",
    rating: 4.7,
    reviews: 89,
    features: [
      { icon: <Sparkle className="w-4 h-4" />, text: "Microwave safe" },
      { icon: <Sparkle className="w-4 h-4" />, text: "Unique glaze pattern" },
    ],
    price: "$20",
    unitPrice: "$20/pc",
    deliveryDate: "May 11",
    shippingLocation: "USA",
  },
  {
    id: 5,
    title: "Leather Journal",
    image: "/images/journal.jpg",
    rating: 4.9,
    reviews: 102,
    features: [
      { icon: <Sparkle className="w-4 h-4" />, text: "Recycled paper" },
      { icon: <Sparkle className="w-4 h-4" />, text: "Hand-bound cover" },
    ],
    price: "$35",
    unitPrice: "$35/book",
    deliveryDate: "May 13",
    shippingLocation: "Germany",
  },
  {
    id: 6,
    title: "Macrame Plant Hanger",
    image: "/images/macrame.jpg",
    rating: 4.4,
    reviews: 47,
    features: [
      { icon: <Sparkle className="w-4 h-4" />, text: "100% cotton rope" },
      { icon: <Sparkle className="w-4 h-4" />, text: "Supports all pot sizes" },
    ],
    price: "$22",
    unitPrice: "$22/set",
    deliveryDate: "May 16",
    shippingLocation: "Australia",
  },
  {
    id: 7,
    title: "Homemade Jam Set",
    image: "/images/jam.jpg",
    rating: 4.6,
    reviews: 66,
    features: [
      { icon: <Sparkle className="w-4 h-4" />, text: "No preservatives" },
      { icon: <Sparkle className="w-4 h-4" />, text: "3 flavors included" },
    ],
    price: "$25",
    unitPrice: "$8/jar",
    deliveryDate: "May 15",
    shippingLocation: "France",
  },
  {
    id: 8,
    title: "Wooden Cutting Board",
    image: "/images/cuttingboard.jpg",
    rating: 4.3,
    reviews: 39,
    features: [
      { icon: <Sparkle className="w-4 h-4" />, text: "Bamboo material" },
      { icon: <Sparkle className="w-4 h-4" />, text: "Easy to clean" },
    ],
    price: "$28",
    unitPrice: "$28/each",
    deliveryDate: "May 18",
    shippingLocation: "Italy",
  },
];
