import { cosmeticsImage, groceryImage } from "@/assets";
import { Droplet, FlaskConical, Package, Sparkle } from "lucide-react";
import { StaticImageData } from "next/image";
import React from "react";

// Define the type for each product
type ProductFeature = {
  icon: React.ReactNode;
  text: string;
};

export type Product = {
  id: number;
  title: string;
  category: string;
  image: StaticImageData | string; // ✅ Allow StaticImageData or string
  features: ProductFeature[];
  price: string;
  unitPrice: string;
  deliveryDate: string;
  shippingLocation: string;
  rating: number;
  reviews: number;
};
export const products: Product[] = [
  {
    id: 1,
    category: "beauty",
    title: "Korean Skincare Anti-Aging, Dark Spot Wrinkle Minimizing Toner",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <FlaskConical className="..." />, text: "Hydrating..." },
      { icon: <Package className="..." />, text: "Eucalyptus · 100 Count..." },
      { icon: <Droplet className="..." />, text: "9K+ bought..." },
    ],
    price: "$59.95",
    unitPrice: "($0.60 / Count)",
    deliveryDate: "Tue, May 13",
    shippingLocation: "Bangladesh",
    rating: 4.4,
    reviews: 544,
  },
  {
    id: 2,
    category: "grocery",
    title: "Vitamin C Glow Serum with Hyaluronic Acid & Turmeric",
    image: groceryImage.groc,
    features: [
      { icon: <FlaskConical className="..." />, text: "Brightens dull skin..." },
      { icon: <Package className="..." />, text: "1 oz · Dropper Bottle" },
      { icon: <Droplet className="..." />, text: "5K+ bought..." },
    ],
    price: "$24.50",
    unitPrice: "($24.50 / oz)",
    deliveryDate: "Wed, May 15",
    shippingLocation: "USA",
    rating: 4.7,
    reviews: 1021,
  },
  {
    id: 3,
    category: "beauty",
    title: "Herbal Clay Face Mask - Detox & Pore Minimizer",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <FlaskConical className="..." />, text: "Made with Bentonite..." },
      { icon: <Package className="..." />, text: "4 oz · Jar" },
      { icon: <Droplet className="..." />, text: "2K+ bought..." },
    ],
    price: "$18.00",
    unitPrice: "($4.50 / oz)",
    deliveryDate: "Mon, May 12",
    shippingLocation: "India",
    rating: 4.6,
    reviews: 873,
  },
  {
    id: 4,
    category: "grocery",
    title: "Gentle Foaming Cleanser for Sensitive Skin",
    image: groceryImage.groc,
    features: [
      { icon: <FlaskConical className="..." />, text: "Fragrance-free..." },
      { icon: <Package className="..." />, text: "6.7 fl oz · Pump Bottle" },
      { icon: <Droplet className="..." />, text: "8K+ bought..." },
    ],
    price: "$12.99",
    unitPrice: "($1.94 / fl oz)",
    deliveryDate: "Fri, May 10",
    shippingLocation: "Canada",
    rating: 4.5,
    reviews: 675,
  },
  {
    id: 5,
    category: "beauty",
    title: "Handmade Soap",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Sparkle className="..." />, text: "Organic Ingredients" },
      { icon: <Sparkle className="..." />, text: "Scented with Lavender" },
    ],
    price: "$12",
    unitPrice: "$4/oz",
    deliveryDate: "May 10",
    shippingLocation: "USA",
    rating: 4.5,
    reviews: 34,
  },
  {
    id: 6,
    category: "beauty",
    title: "Beeswax Candles",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Sparkle className="..." />, text: "Slow-burning" },
      { icon: <Sparkle className="..." />, text: "Natural fragrance" },
    ],
    price: "$18",
    unitPrice: "$6/each",
    deliveryDate: "May 12",
    shippingLocation: "Canada",
    rating: 4.8,
    reviews: 58,
  },
  {
    id: 7,
    category: "homemade",
    title: "Knitted Scarf",
    image: groceryImage.groc,
    features: [
      { icon: <Sparkle className="..." />, text: "Soft wool blend" },
      { icon: <Sparkle className="..." />, text: "Hand-stitched" },
    ],
    price: "$30",
    unitPrice: "$30/item",
    deliveryDate: "May 14",
    shippingLocation: "UK",
    rating: 4.2,
    reviews: 21,
  },
  {
    id: 8,
    category: "homemade",
    title: "Ceramic Mug",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Sparkle className="..." />, text: "Microwave safe" },
      { icon: <Sparkle className="..." />, text: "Unique glaze pattern" },
    ],
    price: "$20",
    unitPrice: "$20/pc",
    deliveryDate: "May 11",
    shippingLocation: "USA",
    rating: 4.7,
    reviews: 89,
  },
  {
    id: 9,
    category: "homemade",
    title: "Leather Journal",
    image: groceryImage.groc,
    features: [
      { icon: <Sparkle className="..." />, text: "Recycled paper" },
      { icon: <Sparkle className="..." />, text: "Hand-bound cover" },
    ],
    price: "$35",
    unitPrice: "$35/book",
    deliveryDate: "May 13",
    shippingLocation: "Germany",
    rating: 4.9,
    reviews: 102,
  },
  {
    id: 10,
    category: "beauty",
    title: "Macrame Plant Hanger",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Sparkle className="..." />, text: "100% cotton rope" },
      { icon: <Sparkle className="..." />, text: "Supports all pot sizes" },
    ],
    price: "$22",
    unitPrice: "$22/set",
    deliveryDate: "May 16",
    shippingLocation: "Australia",
    rating: 4.4,
    reviews: 47,
  },
  {
    id: 11,
    category: "homemade",
    title: "Homemade Jam Set",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Sparkle className="..." />, text: "No preservatives" },
      { icon: <Sparkle className="..." />, text: "3 flavors included" },
    ],
    price: "$25",
    unitPrice: "$8/jar",
    deliveryDate: "May 15",
    shippingLocation: "France",
    rating: 4.6,
    reviews: 66,
  },
  {
    id: 12,
    category: "homemade",
    title: "Wooden Cutting Board",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Sparkle className="..." />, text: "Bamboo material" },
      { icon: <Sparkle className="..." />, text: "Easy to clean" },
    ],
    price: "$28",
    unitPrice: "$28/each",
    deliveryDate: "May 18",
    shippingLocation: "Italy",
    rating: 4.3,
    reviews: 39,
  },
  {
    id: 13,
    category: "beauty",
    title: "Soothing Aloe Vera Gel",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Droplet className="..." />, text: "Cools and hydrates..." },
      { icon: <FlaskConical className="..." />, text: "Pure Aloe Extract..." },
      { icon: <Package className="..." />, text: "8 fl oz · Tube" },
    ],
    price: "$10.99",
    unitPrice: "($1.37 / fl oz)",
    deliveryDate: "May 16",
    shippingLocation: "USA",
    rating: 4.5,
    reviews: 211,
  },
  {
    id: 14,
    category: "beauty",
    title: "Herbal Lip Balm 4-Pack",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Sparkle className="..." />, text: "Infused with beeswax..." },
      { icon: <Package className="..." />, text: "4 Tubes..." },
      { icon: <Droplet className="..." />, text: "Long-lasting moisture" },
    ],
    price: "$8.99",
    unitPrice: "($2.25 / tube)",
    deliveryDate: "May 17",
    shippingLocation: "Canada",
    rating: 4.6,
    reviews: 142,
  },
  {
    id: 15,
    category: "beauty",
    title: "Aromatherapy Essential Oil Set",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Sparkle className="..." />, text: "Includes Lavender..." },
      { icon: <FlaskConical className="..." />, text: "Steam-distilled..." },
      { icon: <Package className="..." />, text: "Pack of 4" },
    ],
    price: "$22.00",
    unitPrice: "($5.50 / bottle)",
    deliveryDate: "May 19",
    shippingLocation: "UK",
    rating: 4.8,
    reviews: 310,
  },
  {
    id: 16,
    category: "beauty",
    title: "Reusable Cotton Rounds",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Droplet className="..." />, text: "Machine washable..." },
      { icon: <Sparkle className="..." />, text: "Soft bamboo cotton..." },
      { icon: <Package className="..." />, text: "Includes 20 rounds..." },
    ],
    price: "$14.99",
    unitPrice: "($0.75 / round)",
    deliveryDate: "May 20",
    shippingLocation: "Germany",
    rating: 4.7,
    reviews: 98,
  },
  {
    id: 17,
    category: "beauty",
    title: "Mini Jade Roller & Gua Sha Set",
    image: cosmeticsImage.nailPolish,
    features: [
      { icon: <Sparkle className="..." />, text: "Reduces puffiness..." },
      { icon: <Droplet className="..." />, text: "Natural jade stone" },
      { icon: <Package className="..." />, text: "Includes pouch..." },
    ],
    price: "$16.50",
    unitPrice: "$16.50/set",
    deliveryDate: "May 21",
    shippingLocation: "Japan",
    rating: 4.3,
    reviews: 76,
  },
];
